version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  descriptive_analysis:
    run: stata-mp:latest analysis/000_cr_descriptive_cohort.do 
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        table_1: output/tabfig/table_1.csv
        desc_stats: output/tabfig/descriptive_stats.csv
        
  generate_measure_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2021-10-01 by month"
    outputs:
      highly_sensitive:
        measure_data: output/input_measures*.csv

  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_measures
    needs: [generate_measure_cohort]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

  draw_timeseries:
    run: python:latest python analysis/time_series_plots.py
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        graph: output/event_count_time_series.svg
        tables: output/table_*.csv
