version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  import_data:
    run: stata-mp:latest analysis/import_data.do
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        import_data_log: output/logs/import_data.log
      highly_sensitive:
        analysis_dataset: output/analysis_dataset.dta

  run_all:
    needs: [import_data]
    # In order to be valid this action needs to define a run command and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml