version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  import_data:
    run: stata-mp:latest analysis/import_data.do
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        import_data_log: output/logs/import_data.log
      highly_sensitive:
        analysis_dataset: output/analysis_dataset.dta

  derive_ps:
    run: stata-mp:latest analysis/derive_ps.do
    needs: [import_data]
    outputs:
      moderately_sensitive:
        derive_ps_log: output/logs/derive_ps.log
        psplot1: output/tabfig/psplot1.svg
        psplot2: output/tabfig/psplot2.svg
        psplot3: output/tabfig/psplot3.svg
        psplot4: output/tabfig/psplot4.svg
        psplot5: output/tabfig/psplot5.svg
        psplot6: output/tabfig/psplot6.svg
        table_stddiff: output/tabfig/table_stddiff.txt
        table_stddiff2: output/tabfig/table_stddiff2.txt
      highly_sensitive:
        analysis_dataset_ps: output/analysis_dataset_ps.dta

  ps_model_died_covid:
    run: stata-mp:latest analysis/ps_model.do died_covid "death"
    needs: [derive_ps]
    outputs:
      moderately_sensitive:
        log: output/logs/ps_model_died_covid.log
        table2: output/tabfig/table2_died_covid.txt

  ps_model_hospitalised_covid:
    run: stata-mp:latest analysis/ps_model.do hospitalised_covid "hospitalisation"
    needs: [derive_ps]
    outputs:
      moderately_sensitive:
        log: output/logs/ps_model_hospitalised_covid.log
        table2: output/tabfig/table2_hospitalised_covid.txt

  run_all:
    needs: [ps_model_died_covid, ps_model_hospitalised_covid]
    # In order to be valid this action needs to define a run command and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml