version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  descriptive_analyss:
    run: stata-mp:latest analysis/000_cr_descriptive_cohort.do 
    outputs:
      moderately_sensitive:
        table_1: output/tabfig/table_1.csv
        desc_stats: output/tabfig/descriptive_stats.csv
